spring:
  application:
    name: redis
  cloud:
    nacos:
      server-addr: 192.168.1.11:8848
      discovery:
        username: nacos
        password: nacos
        namespace: public
        ephemeral: false # 是否永久实例
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    cache: false
#     filter:
#      stat:
#        log-slow-sql: true
#        slow-sql-millis: 1000
#        merge-sql: false
#      wall:
#        config:
#          multi-statement-allow: true
server:
  port: 8070
